version: "4.0"

actions: 
  generate_dataset_definition_rheum:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_rheum.py --output output/dataset_definition_rheum.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_definition_rheum.csv.gz


  generate_measures_rheum:
    run: ehrql:v1 generate-measures analysis/measures.py --output output/measures/measures.csv
    outputs:
      moderately_sensitive:
        measures: output/measures/measures.csv